"""empty message

Revision ID: 05d0961fa281
Revises: 35a35988824d
Create Date: 2020-09-08 13:35:44.573220

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '05d0961fa281'
down_revision = '35a35988824d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_name', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('role', sa.Enum('admin', 'trader', name='usertype'), nullable=False))
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('user', 'role')
    op.drop_column('user', 'last_name')
    # ### end Alembic commands ###
