"""empty message

Revision ID: 2e6352161a8a
Revises: b5ff3015f5bb
Create Date: 2020-09-16 17:43:23.504622

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2e6352161a8a'
down_revision = 'b5ff3015f5bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchelements',
    sa.Column('watchlist_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watch_list.id'], ),
    sa.PrimaryKeyConstraint('watchlist_id', 'stock_id')
    )
    op.drop_table('watch_element')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watch_element',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stock_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('watchlist_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], name='watch_element_ibfk_1'),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watch_list.id'], name='watch_element_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('watchelements')
    # ### end Alembic commands ###
