"""empty message

Revision ID: 3643e52393a2
Revises: 0a3976494b47
Create Date: 2020-09-09 20:04:30.383944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3643e52393a2'
down_revision = '0a3976494b47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'watch_list', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'watch_list', type_='foreignkey')
    # ### end Alembic commands ###
