"""empty message

Revision ID: 48be451090ce
Revises: e781017458aa
Create Date: 2020-10-02 18:58:23.318314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48be451090ce'
down_revision = 'e781017458aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watch_list', sa.Column('default', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watch_list', 'default')
    # ### end Alembic commands ###
