"""empty message

Revision ID: 807336f0d56b
Revises: 05d0961fa281
Create Date: 2020-09-08 13:38:12.090923

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '807336f0d56b'
down_revision = '05d0961fa281'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=False))
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', mysql.ENUM('admin', 'trader'), nullable=False))
    op.drop_column('user', 'admin')
    # ### end Alembic commands ###
