"""empty message

Revision ID: c85e7a004c7d
Revises: 8f3399457a3e
Create Date: 2020-09-09 19:29:49.901697

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c85e7a004c7d'
down_revision = '8f3399457a3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('element_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('element_list',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('watchlist_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stock_symbol', mysql.VARCHAR(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
