"""empty message

Revision ID: f86886746cce
Revises: 3643e52393a2
Create Date: 2020-09-12 15:15:19.051686

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f86886746cce'
down_revision = '3643e52393a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watch_element', sa.Column('stock_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'watch_element', 'stock', ['stock_id'], ['id'])
    op.drop_column('watch_element', 'stock_symbol')
    op.drop_column('watch_element', 'watchlist_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watch_element', sa.Column('watchlist_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('watch_element', sa.Column('stock_symbol', mysql.VARCHAR(length=12), nullable=True))
    op.drop_constraint(None, 'watch_element', type_='foreignkey')
    op.drop_column('watch_element', 'stock_id')
    # ### end Alembic commands ###
